export const IWADS:any = {
  doom1: {
    label: "Doom 1",
  },
  doom2: {
    remote: "https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/doom2.wad",
    label: "Doom 2",
  },
  tnt: {
    remote: "https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/tnt.wad",
    label: "TNT: Evilution",
  },
  plutonia: {
    remote: "https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/plutonia.wad",
    label: "The Plutonia Experiment",
  },
  doomu: {
    remote: "https://github.com/Akbar30Bill/DOOM_wads/raw/refs/heads/master/doomu.wad",
    label: "The Ultimate Doom",
  },
};

export const ADJECTIVES = [
  "Grumpy",
  "Ecstatic",
  "Surly",
  "Prepared",
  "Crafty",
  "Alert",
  "Sluggish",
  "Testy",
  "Reluctant",
  "Languid",
  "Passive",
  "Pacifist",
  "Aggressive",
  "Hostile",
  "Bubbly",
  "Giggly",
  "Laughing",
  "Crying",
  "Frowning",
  "Torpid",
  "Lethargic",
  "Manic",
  "Patient",
  "Protective",
  "Philosophical",
  "Enquiring",
  "Debating",
  "Furious",
  "Laid-Back",
  "Easy-Going",
  "Cromulent",
  "Excitable",
  "Tired",
  "Exhausted",
  "Ruminating",
  "Redundant",
  "Sporty",
  "Ginger",
  "Scary",
  "Posh",
  "Baby",
];

export const NOUNS = [
  "Frad",
  "Cacodemon",
  "Arch-Vile",
  "Cyberdemon",
  "Imp",
  "Demon",
  "Mancubus",
  "Arachnotron",
  "Baron",
  "Knight",
  "Revenant",
  "Ettin",
  "Maulotaur",
  "Centaur",
  "Afrit",
  "Serpent",
  "Disciple",
  "Gargoyle",
  "Golem",
  "Lich",
  "Sentinel",
  "Acolyte",
  "Templar",
  "Reaver",
  "Spectre",
];

